import Button from "@/components/common/ButtonDefault";
import Head from "next/head";
import Link from "next/link";
import HomeComponent from "@/components/Home";
import { useFetchSession } from "@/hooks/useSession";

export default function Home() {
  const { session } = useFetchSession();
  if (session === undefined) return;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-sky-500">
        <HomeComponent />
      </main>
    </>
  );
}
